//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashik_Hotel_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Bill_ID { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public string Hotel_Name { get; set; }
        public string Address_Hotel { get; set; }
        public string Phone { get; set; }
        public string User_Name { get; set; }
        public Nullable<System.DateTime> Check_in_Date { get; set; }
        public Nullable<System.DateTime> Check_out_Date { get; set; }
        public Nullable<int> Number_of_Rooms { get; set; }
        public string Room_Type { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<int> Total_Days { get; set; }
        public Nullable<int> Total_Points { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual User_Login User_Login { get; set; }
    }
}
