//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashik_Hotel_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int Booking_ID { get; set; }
        public Nullable<System.DateTime> Check_in_Date { get; set; }
        public Nullable<System.DateTime> Check_out_Date { get; set; }
        public Nullable<int> Number_of_Rooms { get; set; }
        public Nullable<int> Adults { get; set; }
        public Nullable<int> Childrens { get; set; }
        public string Room_Type { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<bool> Booking_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual User_Login User_Login { get; set; }
    }
}
