//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashik_Hotel_Reservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_ID { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public string Sender_Name { get; set; }
        public string Sender_Email { get; set; }
        public string Sender_Phone { get; set; }
        public Nullable<System.DateTime> Send_Date { get; set; }
        public string Sender_Message { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
